### ISSUE TITLE
Ensure wasmcloud-operator can enable observability for the hosts it's deploying

### ISSUE THREAD

**Issue by joonas** [wasmCloud/wasmcloud-operator#49]
Since we have built-in support for OTEL, we need to make sure it's possible to enable via the `WasmCloudHostConfig` CRD and provide overrides for the various options.

**Comment by liamwh** [comment]
To add to this:

It would be excellent to be able to configure the means of OTLP exporting also, for example the [Exporter Protocol](https://opentelemetry.io/docs/specs/otel/protocol/exporter/) and the Headers for authorisation.
